const VERSES={
  "1tim4":{ref:"1 Timoteo 4:1",text:"La palabra inspirada dice claramente que, en tiempos futuros, algunos se apartarán de la fe al prestar atención a mensajes inspirados que engañan y a enseñanzas de demonios"},
  "2tim3":{ref:"2 Timoteo 3",text:"En el programa se menciona este capítulo al explicar que en los últimos días muchas personas serían desobedientes a los padres, desleales, no estarían dispuestas a llegar a ningún acuerdo y no tendrían cariño natural.",note:"El texto se menciona en el programa, pero no se lee completo."},
  "col1":{ref:"Colosenses 1:16",text:"Por medio de él todo lo demás fue creado en los cielos y en la tierra, las cosas visibles y las cosas invisibles, ya sean tronos, dominios, gobiernos o autoridades"},
  "gen127":{ref:"Génesis 1:27",text:"Así que Dios pasó a crear al ser humano a su imagen. A la imagen de Dios lo creó. Hombre y mujer los creó"},
  "gen131":{ref:"Génesis 1:31",text:"Después de eso, Dios vio todo lo que había hecho y, ¡miren!, todo era muy bueno. Y hubo tarde y hubo mañana. Ese fue el sexto día"},
  "isa545":{ref:"Isaías 54:5",text:"Y es que tu Gran Creador es como tu esposo —su nombre es Jehová de los ejércitos—"},
  "eph314":{ref:"Efesios 3:14, 15",text:"Por esa razón me arrodillo ante el Padre, a quien toda familia en el cielo y en la tierra le debe su nombre"},
  "jas314":{ref:"Santiago 3:14-16",text:"Pero, si ustedes tienen amargos celos y un espíritu conflictivo en el corazón, no anden alardeando ni mintiendo contra la verdad. Esta no es la sabiduría que viene de arriba; es terrenal, animal, demoníaca. Porque, donde hay celos y un espíritu conflictivo, también habrá desorden y todo tipo de cosas malas"},
  "prov357":{ref:"Proverbios 3:5-7",text:"Confía en Jehová con todo tu corazón y no te apoyes en tu propio entendimiento. Tómalo en cuenta en todos tus caminos, y él hará rectas tus sendas. No te vuelvas sabio a tus propios ojos; teme a Jehová y aléjate del mal"},
  "isa3021":{ref:"Isaías 30:21",text:"Y, en caso de que te desvíes a la derecha o a la izquierda, oirás con tus propios oídos estas palabras detrás de ti: ‘Este es el camino. Anda en él’"},
  "mark1029":{ref:"Marcos 10:29, 30",text:"Les aseguro que no hay nadie que haya dejado hogar, hermanos, hermanas, madre, padre, hijos [...] por mí y por las buenas noticias que no reciba ahora, en este tiempo, 100 veces más —[...] hermanos, hermanas, madres, hijos—"},
  "mark335":{ref:"Marcos 3:35",text:"Todo el que hace la voluntad de Dios es mi hermano y mi hermana y mi madre"},
  "eph51":{ref:"Efesios 5:1, 2",text:"El programa menciona estos versículos para animar a imitar al Padre como hijos amados y seguir el camino del amor.",note:"El texto se menciona en el programa, pero no se lee completo."},
  "prov1522":{ref:"Proverbios 15:22",text:"Con muchos consejeros se consiguen buenos resultados"},
  "ps103":{ref:"Salmo 103:11",text:"Porque, tan alto como está el cielo sobre la tierra, así de inmenso es su amor leal por los que le temen"},
  "isa4817":{ref:"Isaías 48:17",text:"Yo, Jehová, soy tu Dios, el que te enseña por tu propio bien, el que te guía por el camino en que debes andar"},
  "gen392":{ref:"Génesis 39:2",text:"Pero Jehová estaba con José. Así que le fue bien"},
  "gen479":{ref:"Génesis 47:9",text:"Llevo 130 años yendo y viniendo. Pero noten: han sido años muy difíciles"},
  "gen313":{ref:"Génesis 31:3",text:"Jehová le dijo a Jacob que regresara a la tierra de sus padres y a donde estaban sus parientes.",note:"El programa explica el contenido, pero no lee el versículo completo."},
  "gen3235":{ref:"Génesis 32:3-5",text:"Entonces Jacob le envió mensajeros a su hermano, a su hermano Esaú, que estaba en la tierra de Seír, el territorio de Edom, y les dio esta orden: ‘Díganle esto a mi señor, Esaú: Tu siervo Jacob ha dicho: He estado viviendo con Labán todo este tiempo y he conseguido toros, burros y ovejas, así como siervos y siervas. Te envío este mensaje, mi señor, para darte la noticia y así ganarme tu favor’"},
  "gen334":{ref:"Génesis 33:4",text:"Pero Esaú fue corriendo a su encuentro, lo abrazó y lo besó, y los dos se echaron a llorar"},
  "prov1819":{ref:"Proverbios 18:19",text:"Un hermano ofendido es más inaccesible que una ciudad fortificada, y hay pleitos que son como las barras de una fortaleza"},
  "rom1218":{ref:"Romanos 12:18",text:"Si es posible, hasta donde dependa de ustedes, vivan en paz con todos"},
  "zeph23":{ref:"Sofonías 2:3",text:"Busquen a Jehová todos ustedes, los mansos de la tierra",note:"Estas son las palabras que se leen en el programa."},
  "zeph312":{ref:"Sofonías 3:12",text:"El programa explica que Jehová permitiría que los humildes y modestos se refugiaran en él y sobrevivieran al día de juicio.",note:"El texto se menciona, pero no se lee completo."},
  "zeph317":{ref:"Sofonías 3:17",text:"Se alegrará por ti y se sentirá muy feliz. Se quedará en silencio debido a su amor",note:"Estas son las palabras que se leen en el programa."},
  "rom1215":{ref:"Romanos 12:15",text:"Alégrense con los que se alegran; lloren con los que lloran"},
  "jas113":{ref:"Santiago 1:13",text:"Jugraj lo menciona porque le ayuda a ver que el dolor, el sufrimiento y la muerte no vienen de Jehová.",note:"El versículo se menciona, pero no se lee completo."},
  "john316":{ref:"Juan 3:16",text:"Brianne explica que este texto le hizo sentir de manera personal el valor del sacrificio de Jesús.",note:"El versículo se menciona, pero no se lee completo."},
  "rev214":{ref:"Apocalipsis 21:4",text:"Brianne lo relaciona con la esperanza de volver a ver a sus familiares.",note:"El versículo se menciona, pero no se lee completo."},
  "ps3418":{ref:"Salmo 34:18",text:"Brianne dice que este texto muestra que Jehová está cerca de los que tienen el corazón destrozado.",note:"El versículo se menciona, pero no se lee completo."},
  "matt10":{ref:"Mateo 10",text:"Se venden dos gorriones por una moneda de poco valor, ¿no es cierto? Sin embargo, ni uno de ellos cae a tierra sin que su Padre lo sepa",note:"El programa cita estas palabras del capítulo 10."},
  "luke126":{ref:"Lucas 12:6",text:"La referencia aparece visualmente en una tarjeta con un gorrión durante el video musical.",note:"La transcripción no contiene la lectura completa del versículo."}
};

const SECTIONS=[
{title:"El origen de la familia",time:"01:16–05:06",html:`
<p class="lead">El tema del programa es “Protejamos nuestra familia”. Se explica que la familia fue creada por Jehová y que protegerla implica demostrarle amor a él y resistir las ideas que pueden debilitarla.</p>
<div class="flow flow-four"><div class="flow-node blue"><b>Jehová</b><span>El amor lo impulsó a compartir el regalo de la vida.</span></div><span class="flow-arrow">→</span><div class="flow-node lavender"><b>Jesús</b><span>Fue creado primero como un espíritu en el cielo.</span></div><span class="flow-arrow">→</span><div class="flow-node mint"><b>Ángeles</b><span>Millones de hijos espirituales forman la familia celestial.</span></div><span class="flow-arrow">→</span><div class="flow-node amber"><b>Familia humana</b><span>Jehová preparó un hogar para que los humanos formaran familias.</span></div></div>
<div class="soft-grid two"><div class="plain-block"><h3>Por qué protegerla</h3><p>El programa presenta a la familia como una institución que viene de Jehová y explica que Satanás busca dañar lo que procede de Dios.</p></div><div class="plain-block"><h3>La familia celestial</h3><p>Jehová usó a su Hijo primogénito para crear las demás cosas. Los ángeles son descritos como hijos espirituales que forman parte de su familia celestial.</p></div></div>
<div class="verse-row"><button class="verse-chip" data-verse="1tim4">1 Timoteo 4:1</button><button class="verse-chip" data-verse="2tim3">2 Timoteo 3</button><button class="verse-chip" data-verse="col1">Colosenses 1:16</button></div>`},

{title:"La Tierra y la primera pareja",time:"05:07–08:53",html:`
<p class="lead">El relato recorre los seis días creativos y termina con la primera pareja humana. La idea que se destaca es el cuidado con el que Jehová preparó un hogar para la familia humana.</p>
<div class="days-grid"><div class="day-card"><span>Día 1</span><p>Una claridad difusa atraviesa la atmósfera de la Tierra.</p></div><div class="day-card"><span>Día 2</span><p>Se separan las aguas y se forma un espacio abierto.</p></div><div class="day-card"><span>Día 3</span><p>Retroceden las aguas y aparece la tierra seca.</p></div><div class="day-card"><span>Día 4</span><p>El Sol y la Luna empiezan a verse desde la superficie.</p></div><div class="day-card"><span>Día 5</span><p>Se crean animales marinos y aves con capacidad de reproducirse.</p></div><div class="day-card"><span>Día 6</span><p>Se crean animales terrestres y finalmente la primera pareja humana.</p></div></div>
<blockquote class="source-quote"><p><i>Perspicacia</i> explica que al principio de cada período creativo el propósito no era evidente para los observadores angélicos, pero al llegar la “mañana” quedaba claro porque ya se había realizado.</p></blockquote>
<div class="plain-block accent"><h3>Una familia en el cielo y en la Tierra</h3><p>Jehová se compara con un esposo y se presenta como Padre de toda familia. El programa relaciona la organización de la familia humana con su familia celestial.</p></div>
<div class="verse-row"><button class="verse-chip" data-verse="gen127">Génesis 1:27</button><button class="verse-chip" data-verse="gen131">Génesis 1:31</button><button class="verse-chip" data-verse="isa545">Isaías 54:5</button><button class="verse-chip" data-verse="eph314">Efesios 3:14, 15</button></div>`},

{title:"Cómo proteger la familia",time:"08:54–14:01",html:`
<p class="lead">El programa distingue entre ataques evidentes contra la familia y problemas más sutiles que aprovechan nuestras imperfecciones, emociones y falta de tiempo.</p>
<div class="compare"><div class="compare-col rose"><h3>Ataques directos</h3><ul><li>Divorcios sin base bíblica.</li><li>Relaciones sexuales fuera del matrimonio.</li><li>Aborto, abuso de menores y falta de cariño.</li></ul></div><div class="compare-col blue"><h3>Ataques sutiles</h3><ul><li>Celos y espíritu conflictivo.</li><li>Reacciones dominadas por emociones imperfectas.</li><li>Perder tiempo valioso que podría dedicarse a la familia.</li></ul></div></div>
<div class="soft-grid two"><div class="plain-block"><h3>Tiempo y cariño</h3><p>A los padres se les recuerda que ellos mismos son un regalo valioso para sus hijos. También se advierte que las ocupaciones diarias pueden enfriar la relación de un matrimonio.</p></div><div class="plain-block"><h3>Confiar y actuar</h3><p>No basta con saber lo que Jehová enseña. El programa subraya la necesidad de poner en práctica sus principios.</p></div></div>
<div class="two-step"><div><span>1</span><b>“Este es el camino”</b><p>Escuchar lo que Jehová enseña.</p></div><div><span>2</span><b>“Anda en él”</b><p>Aplicar sus principios y leyes.</p></div></div>
<div class="verse-row"><button class="verse-chip" data-verse="jas314">Santiago 3:14-16</button><button class="verse-chip" data-verse="prov357">Proverbios 3:5-7</button><button class="verse-chip" data-verse="isa3021">Isaías 30:21</button></div>`},

{title:"Rut y Noemí",time:"14:02–18:42",html:`
<p class="lead">Rut siguió viviendo con Noemí después de enviudar. Su ejemplo se usa para mostrar que el cariño, el amor y el cuidado no dependen del tamaño de una familia.</p>
<div class="family-diagram"><div class="family-core">Familia espiritual</div><div class="family-spokes"><span>cariño</span><span>lealtad</span><span>cuidado</span><span>amor</span></div></div>
<div class="soft-grid two"><div class="plain-block"><h3>La congregación como familia</h3><p>Jesús recordó que la congregación puede ser una familia para quienes no tienen una familia literal. Por eso los cristianos se llaman entre sí hermano y hermana.</p></div><div class="plain-block"><h3>Mantenerla unida</h3><p>Se aconseja no formar grupos cerrados, no guardar resentimientos y superar malentendidos para proteger el espíritu de familia.</p></div></div>
<div class="plain-block accent"><h3>Una familia universal</h3><p>Se cita una publicación que describe el propósito de una Tierra llena de personas justas y perfectas en relación amorosa y pacífica con el Padre celestial.</p></div>
<div class="verse-row"><button class="verse-chip" data-verse="mark1029">Marcos 10:29, 30</button><button class="verse-chip" data-verse="mark335">Marcos 3:35</button><button class="verse-chip" data-verse="eph51">Efesios 5:1, 2</button></div>`},

{title:"Adoración en familia",time:"18:43–24:50",html:`
<p class="lead">La pizarra animada parte de una realidad común: hay muchas cosas que hacer, poco tiempo y necesidades distintas dentro de una misma familia. La recomendación es planificar sin convertir cada semana en una superproducción.</p>
<div class="advice-strip"><div><b>Necesidades</b><span>Presión de grupo, concentración o ayuda en la predicación.</span></div><div><b>Edades</b><span>Ajustar la duración según la capacidad de concentración.</span></div><div><b>Gustos</b><span>Usar lo que les interesa para enseñar principios bíblicos.</span></div><div><b>Ambiente</b><span>Aprender y pasarla bien juntos.</span></div></div>
<div class="media-carousel" data-carousel><div class="carousel-topline"><span>▶ EXPERIENCIAS</span><span class="carousel-count">1 de 5</span></div><div class="carousel-viewport"><div class="carousel-track"><article class="media-slide"><p class="person">Deborah Peterkin</p><p class="place">Nueva York</p><p>Su papá los llevaba a contemplar las estrellas. El estudio del universo los ayudaba a pensar en cómo es Jehová, no solo a acumular datos.</p></article><article class="media-slide"><p class="person">Sandra Brown</p><p class="place">Connecticut</p><p>Relaciona esos recuerdos con la oración y recuerda cuánto se reían juntos durante la adoración en familia.</p></article><article class="media-slide"><p class="person">Cyrus Cutrer</p><p class="place">Nueva York</p><p>Un ambiente relajado le permitió hablar de temas que le daban vergüenza, practicar situaciones difíciles y proponer temas.</p></article><article class="media-slide"><p class="person">Jackie García</p><p class="place">Nueva Jersey</p><p>Adapta los temas a hijos de distintas edades y maneras de aprender. La serie sobre Jesús motivó mucho a su hijo Zion.</p></article><article class="media-slide"><p class="person">Rubén Fontanez</p><p class="place">Pensilvania</p><p>Usa <i>Las buenas noticias según Jesús</i> y hace pausas para buscar aplicaciones prácticas, especialmente con su hija Michaela.</p></article></div></div><div class="carousel-controls"><button class="carousel-btn prev" aria-label="Anterior">←</button><div class="carousel-dots" aria-hidden="true"></div><button class="carousel-btn next" aria-label="Siguiente">→</button></div></div>
<div class="planner-card"><div class="planner-title"><div><p class="eyebrow">Plan personal</p><h3>Adoración en familia</h3></div><span class="saved-state" id="saveState" aria-live="polite"></span></div><div class="planner-grid"><label>Necesidad espiritual<input id="needInput" type="text" placeholder="Ej.: resistir la presión de grupo"></label><label>Tema o actividad<input id="topicInput" type="text" placeholder="Ej.: practicar situaciones difíciles"></label><label>Video de apoyo<input id="videoInput" type="text" placeholder="Ej.: Las buenas noticias según Jesús"></label><label>Aplicación<textarea id="applyInput" rows="3" placeholder="Ej.: buscar una idea para poner en práctica"></textarea></label></div><div class="planner-actions"><button class="app-button primary" id="savePlanner">Guardar</button><button class="app-button" id="clearPlanner">Limpiar</button></div></div>
<div class="verse-row"><button class="verse-chip" data-verse="prov1522">Proverbios 15:22</button></div>`},

{title:"Sarah, Abenezer y Sophie",time:"24:51–30:26",html:`
<p class="lead">Tres jóvenes cuentan qué obstáculo afrontaron, qué les ayudó y qué ocurrió después. Los tres llegaron a ver a Jehová como un Padre y fortalecieron su relación personal con él.</p>
<div class="story-grid"><article class="story-card"><div class="story-head"><span>S</span><div><h3>Sarah</h3><p>Kenia</p></div></div><dl><div><dt>Lo que le pasaba</dt><dd>Era muy tímida y se sentía sola; deseaba tener un padre con quien pudiera desahogarse.</dd></div><div><dt>Qué le ayudó</dt><dd>Isaías 48:17 y el video <i>Borra la tristeza</i> le hicieron sentir que Jehová la entendía y la guiaba.</dd></div><div><dt>Qué pasó después</dt><dd>Empezó a leer más la Biblia, asistir con regularidad a las reuniones, se bautizó y encontró muchos amigos.</dd></div></dl><div class="verse-row"><button class="verse-chip" data-verse="isa4817">Isaías 48:17</button></div></article>
<article class="story-card"><div class="story-head"><span>A</span><div><h3>Abenezer</h3><p>Etiopía</p></div></div><dl><div><dt>Lo que le pasaba</dt><dd>Su familia lo animaba a estudiar en el extranjero y eso lo dejó confundido y frenó su progreso espiritual.</dd></div><div><dt>Qué le ayudó</dt><dd>El ejemplo de José le mostró que su bienestar dependía de mantenerse leal a Jehová, no del prestigio de una escuela.</dd></div><div><dt>Qué pasó después</dt><dd>No se fue al extranjero; aprendió mecánica, se bautizó y seis meses más tarde se hizo precursor regular.</dd></div></dl><div class="verse-row"><button class="verse-chip" data-verse="gen392">Génesis 39:2</button></div></article>
<article class="story-card"><div class="story-head"><span>S</span><div><h3>Sophie</h3><p>Kenia</p></div></div><dl><div><dt>Lo que le pasaba</dt><dd>Se molestó cuando no pudo ser publicadora y se alejó de Jehová durante casi 5 años.</dd></div><div><dt>Qué le ayudó</dt><dd>Salmo 103:11 la ayudó a ver a Jehová como un Padre cariñoso, compasivo y protector.</dd></div><div><dt>Qué pasó después</dt><dd>Volvió a orar, se hizo publicadora, avanzó hasta el bautismo y encontró alegría en la congregación y Betel.</dd></div></dl><div class="verse-row"><button class="verse-chip" data-verse="ps103">Salmo 103:11</button></div></article></div>`},

{title:"6 lecciones para recuperar la paz",time:"30:27–40:35",html:`
<p class="lead">Gary Breaux analiza la relación de Jacob y Esaú para explicar qué puede hacerse cuando parece muy difícil recuperar la paz en una familia. Antes de las seis ideas, advierte que no conviene pensar que uno siempre es “Jacob” y el otro “Esaú”.</p>
<div class="lesson-stack"><article><span>1</span><div><h3>Dar tiempo</h3><p>Pasaron 20 años antes de que Esaú estuviera dispuesto a arreglar las cosas. La confianza puede recuperarse con pequeños pasos regulares.</p></div></article><article><span>2</span><div><h3>Centrarse en hacer la voluntad de Jehová</h3><p>Durante esos años Jacob siguió adelante con lo que Jehová esperaba de él.</p></div></article><article><span>3</span><div><h3>Buscar la guía de Jehová</h3><p>Jacob esperó el momento adecuado, oró y luego tomó la iniciativa para comunicarse con Esaú.</p></div></article><article><span>4</span><div><h3>Mostrar respeto</h3><p>No habló mal de Esaú ante su familia. Se refirió a él con respeto y se fijó en la manera de acercarse.</p></div></article><article><span>5</span><div><h3>Dejar atrás el pasado</h3><p>Jacob llegó en son de paz, se humilló y no volvió a meter el dedo en la llaga.</p></div></article><article><span>6</span><div><h3>No esperar una disculpa</h3><p>La Biblia no dice que Esaú pidiera perdón. El consejo es valorar que vuelva a existir comunicación y mantener abierta la posibilidad de reconciliación.</p></div></article></div>
<div class="peace-ending"><b>Hasta donde dependa de nosotros</b><p>Si la otra persona no acepta nuestros esfuerzos, el discurso anima a no cerrar la puerta y a seguir aplicando Romanos 12:18.</p></div>
<div class="verse-row"><button class="verse-chip" data-verse="gen479">Génesis 47:9</button><button class="verse-chip" data-verse="gen313">Génesis 31:3</button><button class="verse-chip" data-verse="gen3235">Génesis 32:3-5</button><button class="verse-chip" data-verse="gen334">Génesis 33:4</button><button class="verse-chip" data-verse="prov1819">Proverbios 18:19</button><button class="verse-chip" data-verse="rom1218">Romanos 12:18</button></div>`},

{title:"Descubramos más tesoros: Sofonías",time:"40:36–47:46",html:`
<p class="lead">Una dramatización de adoración en familia muestra cómo estudiar el libro de Sofonías para conocer mejor a Jehová. La conversación se centra en personas fieles que podían sentirse invisibles en una época de mucha maldad.</p>
<div class="study-tools"><div><span>1</span><b>Guía de estudio</b><p>Buscar información que ayude a entender mejor el texto.</p></div><div><span>2</span><b>Notas</b><p>Examinar matices de las expresiones bíblicas.</p></div><div><span>3</span><b>Cómo es Jehová</b><p>No quedarse solo con datos; pensar en su personalidad y sentimientos.</p></div></div>
<div class="soft-grid two"><div class="plain-block"><h3>“Busquen a Jehová”</h3><p>La familia concluye que buscarlo no consiste únicamente en aprender datos: implica forjar y conservar una relación personal estrecha con él.</p></div><div class="plain-block"><h3>“Se quedará en silencio debido a su amor”</h3><p>La explicación relaciona esa expresión con sentimientos profundos. La idea que se destaca es que Jehová valora a quienes lo buscan y se alegra por su fidelidad.</p></div></div>
<div class="plain-block accent"><h3>Cuando alguien se siente invisible</h3><p>El padre habla de sentirse invisible en el trabajo; en una escena paralela, una joven expresa pensamientos negativos y recibe ayuda para comparar esos pensamientos con lo que la Biblia dice de los sentimientos de Jehová.</p></div>
<div class="verse-row"><button class="verse-chip" data-verse="zeph23">Sofonías 2:3</button><button class="verse-chip" data-verse="zeph312">Sofonías 3:12</button><button class="verse-chip" data-verse="zeph317">Sofonías 3:17</button></div>`},

{title:"Cuando muere un ser querido",time:"47:47–54:30",html:`
<p class="lead">Jugraj Padda, Harman Padda y Brianne Wade cuentan cómo vivieron pérdidas muy dolorosas. Hablan con franqueza de enojo, confusión, ansiedad, culpa y tristeza, y explican qué los ayudó.</p>
<div class="interview-grid"><article><h3>Jugraj Padda · Canadá</h3><p><b>Lo que sintió:</b> confusión, enojo y preguntas después de la muerte inesperada de su padre.</p><p><b>Qué le ayudó:</b> un hermano le sugirió tres cosas: orar, meditar e imaginar el momento de la resurrección.</p></article><article><h3>Harman Padda · Canadá</h3><p><b>Lo que sintió:</b> enojo, decepción, ansiedad, impotencia y la responsabilidad de ayudar a sus hermanos menores.</p><p><b>Qué le ayudó:</b> la congregación y mantener su rutina de reuniones, predicación y adoración en familia.</p></article><article><h3>Brianne Wade · Canadá</h3><p><b>Lo que sintió:</b> perdió a su tía, abuela y prima; enterró sus emociones y lloraba cuando estaba sola.</p><p><b>Qué le ayudó:</b> una visita de pastoreo y una oración muy sincera en la que le contó a Jehová todo lo que sentía.</p></article></div>
<div class="soft-grid two"><div class="plain-block"><h3>Apoyo de la congregación</h3><p>Harman destaca que los hermanos se convirtieron en su familia. También señala que para recibir ayuda hace falta abrirse y contar cómo uno se siente.</p></div><div class="plain-block"><h3>Esperanza y consuelo</h3><p>Las experiencias muestran cómo la oración, la meditación, la esperanza de la resurrección y los relatos bíblicos fortalecieron su confianza.</p></div></div>
<div class="verse-row"><button class="verse-chip" data-verse="rom1215">Romanos 12:15</button><button class="verse-chip" data-verse="jas113">Santiago 1:13</button><button class="verse-chip" data-verse="john316">Juan 3:16</button><button class="verse-chip" data-verse="rev214">Apocalipsis 21:4</button><button class="verse-chip" data-verse="ps3418">Salmo 34:18</button><button class="verse-chip" data-verse="matt10">Mateo 10</button></div>`},

{title:"Tú vales más que los gorriones",time:"54:31–58:32",html:`
<p class="lead">El video musical recuerda que el valor de una persona ante Jehová no depende de cuánto pueda hacer ahora. La historia visual sigue a una pareja mayor y muestra cariño, recuerdos de servicio, enfermedad, apoyo de la congregación y recuperación.</p>
<div class="music-story"><div class="music-icon" aria-hidden="true">♪</div><div class="music-beats"><div><span>Recuerdos</span><p>La pareja revisa un álbum de sus años de juventud y servicio de tiempo completo.</p></div><div><span>Enfermedad</span><p>El hermano es hospitalizado y su esposa permanece a su lado.</p></div><div><span>Cariño</span><p>Recibe tarjetas y dibujos de ánimo de niños de la congregación.</p></div><div><span>Regreso</span><p>Se recupera, vuelve a casa y comparte una cena con hermanos de la congregación.</p></div></div></div>
<div class="plain-block accent"><h3>Idea del video</h3><p>Aunque una persona ya no pueda hacer tanto como antes, Jehová sigue valorando cada esfuerzo, su lealtad, obediencia y amor.</p></div>
<div class="verse-row"><button class="verse-chip" data-verse="luke126">Lucas 12:6</button></div>`},

{title:"Resumen del programa",time:"58:33–59:15",html:`
<p class="lead">Ralph Walls repasa cuatro ideas principales antes de la videopostal final.</p>
<div class="summary-cards"><div><span>1</span><p>La familia forma parte del propósito de Jehová y todos pueden colaborar para protegerla.</p></div><div><span>2</span><p>Sofonías pudo sentirse solo, pero Jehová valoraba sus esfuerzos por servirle.</p></div><div><span>3</span><p>Sarah, Abenezer y Sophie no permitieron que sus obstáculos les impidieran acercarse a Jehová.</p></div><div><span>4</span><p>La familia espiritual cobra especial importancia cuando muere alguien a quien queremos.</p></div></div>`},

{title:"Videopostal: Chipre",time:"59:16–62:42",html:`
<p class="lead">La videopostal presenta la isla de Chipre, sus paisajes, cultura, comida y la historia de la predicación desde el siglo primero hasta la actualidad.</p>
<div class="data-grid"><div><b>65 km</b><span>al sur de Turquía</span></div><div><b>+300</b><span>días de sol al año</span></div><div><b>+3 200</b><span>publicadores en Chipre</span></div><div><b>39</b><span>congregaciones</span></div><div><b>14</b><span>grupos</span></div><div><b>14</b><span>idiomas</span></div></div>
<div class="culture-strip"><span>lefkaritika</span><span>halloumi</span><span>souvla</span><span>Commandaria</span></div>
<div class="timeline"><article><time>Siglo I</time><p>Pablo y Bernabé llevan las buenas noticias a Chipre.</p></article><article><time>1924</time><p>Cyrus Charalambous regresa de Estados Unidos con publicaciones y las envía desde Nicosia.</p></article><article><time>Década de 1930</time><p>Se forma la primera congregación en Xylophagou.</p></article><article><time>1947</time><p>Llega Antonios Karandinos, misionero graduado de Galaad.</p></article><article><time>1948</time><p>Ya hay 59 publicadores y se abre una sucursal.</p></article><article><time>Década de 1960</time><p>Jóvenes que rechazan el servicio militar son encarcelados e incluso torturados.</p></article><article><time>1974</time><p>Unos 300 hermanos tienen que abandonar sus hogares por la guerra y reciben ayuda internacional.</p></article><article><time>Actualidad</time><p>La predicación continúa en numerosos idiomas y ya se celebró la primera Escuela para Evangelizadores del Reino del país.</p></article></div>
<div class="pafos-card"><div><p class="eyebrow">Pafos</p><h3>Una ciudad ligada al relato bíblico</h3><p>Allí el procónsul Sergio Paulo se hizo creyente después de que Pablo y Bernabé le predicaran.</p></div><div class="pafos-stats"><span><b>431</b> publicadores</span><span><b>5</b> congregaciones</span><span><b>3</b> grupos</span><span><b>7</b> idiomas</span><span><b>85</b> sirven a tiempo completo</span></div></div>`}
];
